title: Alessandro Roic
description: >-
  Personal website built with Vue, designed and developed to showcase my skills and latest projects
url : https://alessandroroic.github.io
github_username:  AlessandroRoic

