title: Alessandro Roic
description: >-
  Personal website built with Vue 3, designed and developed to showcase my skills and latest projects, check it out it's free!
url : https://alessandroroic.github.io
github_username:  AlessandroRoic

